// Auto-generated file - DO NOT EDIT
// Generated by generate-index.js

import { BarbariansCampCleared } from './BarbariansCampCleared.js';
import { BarbariansCampFounded } from './BarbariansCampFounded.js';
import { BarbariansSpawnedUnit } from './BarbariansSpawnedUnit.js';
import { BuildFinished } from './BuildFinished.js';
import { CapitalChanged } from './CapitalChanged.js';
import { ChangeGoldenAgeProgressMeter } from './ChangeGoldenAgeProgressMeter.js';
import { CircumnavigatedGlobe } from './CircumnavigatedGlobe.js';
import { CityBeginsWLTKD } from './CityBeginsWLTKD.js';
import { CityBoughtPlot } from './CityBoughtPlot.js';
import { CityCaptureComplete } from './CityCaptureComplete.js';
import { CityConstructed } from './CityConstructed.js';
import { CityConvertsPantheon } from './CityConvertsPantheon.js';
import { CityConvertsReligion } from './CityConvertsReligion.js';
import { CityCreated } from './CityCreated.js';
import { CityEndsWLTKD } from './CityEndsWLTKD.js';
import { CityEventActivated } from './CityEventActivated.js';
import { CityEventChoiceActivated } from './CityEventChoiceActivated.js';
import { CityEventChoiceEnded } from './CityEventChoiceEnded.js';
import { CityExtendsWLTKD } from './CityExtendsWLTKD.js';
import { CityFlipped } from './CityFlipped.js';
import { CityInvestedBuilding } from './CityInvestedBuilding.js';
import { CityInvestedUnit } from './CityInvestedUnit.js';
import { CityPrepared } from './CityPrepared.js';
import { CityProjectComplete } from './CityProjectComplete.js';
import { CityPuppeted } from './CityPuppeted.js';
import { CityRazed } from './CityRazed.js';
import { CitySoldBuilding } from './CitySoldBuilding.js';
import { CityTrained } from './CityTrained.js';
import { CombatEnded } from './CombatEnded.js';
import { CombatResult } from './CombatResult.js';
import { ContractEnded } from './ContractEnded.js';
import { ContractStarted } from './ContractStarted.js';
import { ContractsRefreshed } from './ContractsRefreshed.js';
import { DealMade } from './DealMade.js';
import { DeclareWar } from './DeclareWar.js';
import { ElectionResultFailure } from './ElectionResultFailure.js';
import { ElectionResultSuccess } from './ElectionResultSuccess.js';
import { EspionageNotificationData } from './EspionageNotificationData.js';
import { EspionageResult } from './EspionageResult.js';
import { EspionageState } from './EspionageState.js';
import { EventActivated } from './EventActivated.js';
import { EventChoiceActivated } from './EventChoiceActivated.js';
import { EventChoiceEnded } from './EventChoiceEnded.js';
import { EventUnitCreated } from './EventUnitCreated.js';
import { GameCoreTestVictory } from './GameCoreTestVictory.js';
import { GameCoreUpdateBegin } from './GameCoreUpdateBegin.js';
import { GameCoreUpdateEnd } from './GameCoreUpdateEnd.js';
import { GameSave } from './GameSave.js';
import { GatherPerTurnReplayStats } from './GatherPerTurnReplayStats.js';
import { GoodyHutReceivedBonus } from './GoodyHutReceivedBonus.js';
import { GoodyHutTechResearched } from './GoodyHutTechResearched.js';
import { GovernmentCooldownChanges } from './GovernmentCooldownChanges.js';
import { GovernmentCooldownRateChanges } from './GovernmentCooldownRateChanges.js';
import { GreatPersonExpended } from './GreatPersonExpended.js';
import { GreatWorkCreated } from './GreatWorkCreated.js';
import { HumanDecision } from './HumanDecision.js';
import { IdeologyAdopted } from './IdeologyAdopted.js';
import { IdeologySwitched } from './IdeologySwitched.js';
import { LoyaltyStateChanged } from './LoyaltyStateChanged.js';
import { MakePeace } from './MakePeace.js';
import { MinorAlliesChanged } from './MinorAlliesChanged.js';
import { MinorFriendsChanged } from './MinorFriendsChanged.js';
import { MinorGift } from './MinorGift.js';
import { MinorGiftUnit } from './MinorGiftUnit.js';
import { NaturalWonderDiscovered } from './NaturalWonderDiscovered.js';
import { NuclearDetonation } from './NuclearDetonation.js';
import { PantheonFounded } from './PantheonFounded.js';
import { ParadropAt } from './ParadropAt.js';
import { PietyChanged } from './PietyChanged.js';
import { PietyRateChanged } from './PietyRateChanged.js';
import { PlaceResource } from './PlaceResource.js';
import { PlayerAdoptPolicy } from './PlayerAdoptPolicy.js';
import { PlayerAdoptPolicyBranch } from './PlayerAdoptPolicyBranch.js';
import { PlayerAdoptsCurrency } from './PlayerAdoptsCurrency.js';
import { PlayerAdoptsGovernment } from './PlayerAdoptsGovernment.js';
import { PlayerAnarchy } from './PlayerAnarchy.js';
import { PlayerBoughtOut } from './PlayerBoughtOut.js';
import { PlayerBuilding } from './PlayerBuilding.js';
import { PlayerBuilt } from './PlayerBuilt.js';
import { PlayerBullied } from './PlayerBullied.js';
import { PlayerCityFounded } from './PlayerCityFounded.js';
import { PlayerDoTurn } from './PlayerDoTurn.js';
import { PlayerDoneTurn } from './PlayerDoneTurn.js';
import { PlayerEndOfMayaLongCount } from './PlayerEndOfMayaLongCount.js';
import { PlayerEndTurnCompleted } from './PlayerEndTurnCompleted.js';
import { PlayerEndTurnInitiated } from './PlayerEndTurnInitiated.js';
import { PlayerGifted } from './PlayerGifted.js';
import { PlayerGoldenAge } from './PlayerGoldenAge.js';
import { PlayerLiberated } from './PlayerLiberated.js';
import { PlayerPlunderedTradeRoute } from './PlayerPlunderedTradeRoute.js';
import { PlayerPreAIUnitUpdate } from './PlayerPreAIUnitUpdate.js';
import { PlayerProtected } from './PlayerProtected.js';
import { PlayerRevoked } from './PlayerRevoked.js';
import { PlayerSecularizes } from './PlayerSecularizes.js';
import { PlayerTradeRouteCompleted } from './PlayerTradeRouteCompleted.js';
import { PlayerVictory } from './PlayerVictory.js';
import { ProvinceLevelChanged } from './ProvinceLevelChanged.js';
import { PushingMissionTo } from './PushingMissionTo.js';
import { RebaseTo } from './RebaseTo.js';
import { ReformCooldownChanges } from './ReformCooldownChanges.js';
import { ReformCooldownRateChanges } from './ReformCooldownRateChanges.js';
import { ReligionEnhanced } from './ReligionEnhanced.js';
import { ReligionFounded } from './ReligionFounded.js';
import { ReligionReformed } from './ReligionReformed.js';
import { ResolutionResult } from './ResolutionResult.js';
import { SetAlly } from './SetAlly.js';
import { SetPopulation } from './SetPopulation.js';
import { StateReligionAdopted } from './StateReligionAdopted.js';
import { StateReligionChanged } from './StateReligionChanged.js';
import { StealPlot } from './StealPlot.js';
import { TeamMeet } from './TeamMeet.js';
import { TeamSetEra } from './TeamSetEra.js';
import { TeamSetHasTech } from './TeamSetHasTech.js';
import { TeamTechResearched } from './TeamTechResearched.js';
import { TerraformingMap } from './TerraformingMap.js';
import { TerraformingPlot } from './TerraformingPlot.js';
import { TestEvent } from './TestEvent.js';
import { TileFeatureChanged } from './TileFeatureChanged.js';
import { TileImprovementChanged } from './TileImprovementChanged.js';
import { TileOwnershipChanged } from './TileOwnershipChanged.js';
import { TileRevealed } from './TileRevealed.js';
import { TileRouteChanged } from './TileRouteChanged.js';
import { TurnComplete } from './TurnComplete.js';
import { UiDiploEvent } from './UiDiploEvent.js';
import { UnitCaptured } from './UnitCaptured.js';
import { UnitCityFounded } from './UnitCityFounded.js';
import { UnitConverted } from './UnitConverted.js';
import { UnitCreated } from './UnitCreated.js';
import { UnitGetSpecialExploreTarget } from './UnitGetSpecialExploreTarget.js';
import { UnitKilledInCombat } from './UnitKilledInCombat.js';
import { UnitPrekill } from './UnitPrekill.js';
import { UnitPromoted } from './UnitPromoted.js';
import { UnitSetXY } from './UnitSetXY.js';
import { UnitUpgraded } from './UnitUpgraded.js';

export const eventSchemas = {
  'BarbariansCampCleared': BarbariansCampCleared,
  'BarbariansCampFounded': BarbariansCampFounded,
  'BarbariansSpawnedUnit': BarbariansSpawnedUnit,
  'BuildFinished': BuildFinished,
  'CapitalChanged': CapitalChanged,
  'ChangeGoldenAgeProgressMeter': ChangeGoldenAgeProgressMeter,
  'CircumnavigatedGlobe': CircumnavigatedGlobe,
  'CityBeginsWLTKD': CityBeginsWLTKD,
  'CityBoughtPlot': CityBoughtPlot,
  'CityCaptureComplete': CityCaptureComplete,
  'CityConstructed': CityConstructed,
  'CityConvertsPantheon': CityConvertsPantheon,
  'CityConvertsReligion': CityConvertsReligion,
  'CityCreated': CityCreated,
  'CityEndsWLTKD': CityEndsWLTKD,
  'CityEventActivated': CityEventActivated,
  'CityEventChoiceActivated': CityEventChoiceActivated,
  'CityEventChoiceEnded': CityEventChoiceEnded,
  'CityExtendsWLTKD': CityExtendsWLTKD,
  'CityFlipped': CityFlipped,
  'CityInvestedBuilding': CityInvestedBuilding,
  'CityInvestedUnit': CityInvestedUnit,
  'CityPrepared': CityPrepared,
  'CityProjectComplete': CityProjectComplete,
  'CityPuppeted': CityPuppeted,
  'CityRazed': CityRazed,
  'CitySoldBuilding': CitySoldBuilding,
  'CityTrained': CityTrained,
  'CombatEnded': CombatEnded,
  'CombatResult': CombatResult,
  'ContractEnded': ContractEnded,
  'ContractStarted': ContractStarted,
  'ContractsRefreshed': ContractsRefreshed,
  'DealMade': DealMade,
  'DeclareWar': DeclareWar,
  'ElectionResultFailure': ElectionResultFailure,
  'ElectionResultSuccess': ElectionResultSuccess,
  'EspionageNotificationData': EspionageNotificationData,
  'EspionageResult': EspionageResult,
  'EspionageState': EspionageState,
  'EventActivated': EventActivated,
  'EventChoiceActivated': EventChoiceActivated,
  'EventChoiceEnded': EventChoiceEnded,
  'EventUnitCreated': EventUnitCreated,
  'GameCoreTestVictory': GameCoreTestVictory,
  'GameCoreUpdateBegin': GameCoreUpdateBegin,
  'GameCoreUpdateEnd': GameCoreUpdateEnd,
  'GameSave': GameSave,
  'GatherPerTurnReplayStats': GatherPerTurnReplayStats,
  'GoodyHutReceivedBonus': GoodyHutReceivedBonus,
  'GoodyHutTechResearched': GoodyHutTechResearched,
  'GovernmentCooldownChanges': GovernmentCooldownChanges,
  'GovernmentCooldownRateChanges': GovernmentCooldownRateChanges,
  'GreatPersonExpended': GreatPersonExpended,
  'GreatWorkCreated': GreatWorkCreated,
  'HumanDecision': HumanDecision,
  'IdeologyAdopted': IdeologyAdopted,
  'IdeologySwitched': IdeologySwitched,
  'LoyaltyStateChanged': LoyaltyStateChanged,
  'MakePeace': MakePeace,
  'MinorAlliesChanged': MinorAlliesChanged,
  'MinorFriendsChanged': MinorFriendsChanged,
  'MinorGift': MinorGift,
  'MinorGiftUnit': MinorGiftUnit,
  'NaturalWonderDiscovered': NaturalWonderDiscovered,
  'NuclearDetonation': NuclearDetonation,
  'PantheonFounded': PantheonFounded,
  'ParadropAt': ParadropAt,
  'PietyChanged': PietyChanged,
  'PietyRateChanged': PietyRateChanged,
  'PlaceResource': PlaceResource,
  'PlayerAdoptPolicy': PlayerAdoptPolicy,
  'PlayerAdoptPolicyBranch': PlayerAdoptPolicyBranch,
  'PlayerAdoptsCurrency': PlayerAdoptsCurrency,
  'PlayerAdoptsGovernment': PlayerAdoptsGovernment,
  'PlayerAnarchy': PlayerAnarchy,
  'PlayerBoughtOut': PlayerBoughtOut,
  'PlayerBuilding': PlayerBuilding,
  'PlayerBuilt': PlayerBuilt,
  'PlayerBullied': PlayerBullied,
  'PlayerCityFounded': PlayerCityFounded,
  'PlayerDoTurn': PlayerDoTurn,
  'PlayerDoneTurn': PlayerDoneTurn,
  'PlayerEndOfMayaLongCount': PlayerEndOfMayaLongCount,
  'PlayerEndTurnCompleted': PlayerEndTurnCompleted,
  'PlayerEndTurnInitiated': PlayerEndTurnInitiated,
  'PlayerGifted': PlayerGifted,
  'PlayerGoldenAge': PlayerGoldenAge,
  'PlayerLiberated': PlayerLiberated,
  'PlayerPlunderedTradeRoute': PlayerPlunderedTradeRoute,
  'PlayerPreAIUnitUpdate': PlayerPreAIUnitUpdate,
  'PlayerProtected': PlayerProtected,
  'PlayerRevoked': PlayerRevoked,
  'PlayerSecularizes': PlayerSecularizes,
  'PlayerTradeRouteCompleted': PlayerTradeRouteCompleted,
  'PlayerVictory': PlayerVictory,
  'ProvinceLevelChanged': ProvinceLevelChanged,
  'PushingMissionTo': PushingMissionTo,
  'RebaseTo': RebaseTo,
  'ReformCooldownChanges': ReformCooldownChanges,
  'ReformCooldownRateChanges': ReformCooldownRateChanges,
  'ReligionEnhanced': ReligionEnhanced,
  'ReligionFounded': ReligionFounded,
  'ReligionReformed': ReligionReformed,
  'ResolutionResult': ResolutionResult,
  'SetAlly': SetAlly,
  'SetPopulation': SetPopulation,
  'StateReligionAdopted': StateReligionAdopted,
  'StateReligionChanged': StateReligionChanged,
  'StealPlot': StealPlot,
  'TeamMeet': TeamMeet,
  'TeamSetEra': TeamSetEra,
  'TeamSetHasTech': TeamSetHasTech,
  'TeamTechResearched': TeamTechResearched,
  'TerraformingMap': TerraformingMap,
  'TerraformingPlot': TerraformingPlot,
  'TestEvent': TestEvent,
  'TileFeatureChanged': TileFeatureChanged,
  'TileImprovementChanged': TileImprovementChanged,
  'TileOwnershipChanged': TileOwnershipChanged,
  'TileRevealed': TileRevealed,
  'TileRouteChanged': TileRouteChanged,
  'TurnComplete': TurnComplete,
  'UiDiploEvent': UiDiploEvent,
  'UnitCaptured': UnitCaptured,
  'UnitCityFounded': UnitCityFounded,
  'UnitConverted': UnitConverted,
  'UnitCreated': UnitCreated,
  'UnitGetSpecialExploreTarget': UnitGetSpecialExploreTarget,
  'UnitKilledInCombat': UnitKilledInCombat,
  'UnitPrekill': UnitPrekill,
  'UnitPromoted': UnitPromoted,
  'UnitSetXY': UnitSetXY,
  'UnitUpgraded': UnitUpgraded,
};

export type EventName = keyof typeof eventSchemas;
